apiVersion: mq.ibm.com/v1beta1
kind: QueueManager
metadata:
  name: $INSTANCE_NAME
  namespace: $TARGET_NAMESPACE
spec:
  version: $MQ_VERSION
  license:
    accept: $LICENSE_ACCEPT
    license: $LICENSE
    use: $LICENSE_TYPE
  web:
    enabled: true
  queueManager:
    name: $QUEUE_MANAGER_NAME
    mqsc:
    - configMap:
        name: mq-cluster-conf
        items:
        - common.mqsc
        - $INSTANCE_NAME.mqsc
    ini:
    - configMap:
        name: mq-cluster-conf
        items:
        - qm.ini
    storage:
      queueManager:
        type: persistent-claim
      defaultClass: $STORAGE_CLASS
